import { 
  LayoutDashboard, 
  User, 
  Briefcase, 
  FileText, 
  Activity, 
  MessageSquare, 
  Award, 
  Bell, 
  Settings,
  Building2,
  PlusCircle,
  Users,
  CheckSquare,
  ClipboardList,
  Calendar,
  UserCheck,
  ShieldCheck,
  FileCheck,
  BarChart3,
  XCircle
} from "lucide-react";

export const sidebarConfig = {
  candidate: [
    { label: "Dashboard Home", href: "/dashboard/candidate", icon: LayoutDashboard },
    { label: "My Profile", href: "/profile", icon: User },
    { label: "Find Jobs", href: "/jobs", icon: Briefcase },
    { label: "My Applications", href: "/dashboard/candidate/applications", icon: FileText },
    { label: "Skill Tests", href: "/skill-test", icon: Activity },
    { label: "Communication Tests", href: "/communication", icon: MessageSquare },
    { label: "Certificates / Badge", href: "/verification", icon: Award },
    { label: "Notifications", href: "/notifications", icon: Bell },
    { label: "Settings", href: "/settings", icon: Settings },
  ],
  recruiter: [
    { label: "Dashboard Home", href: "/dashboard/recruiter", icon: LayoutDashboard },
    { label: "Company Profile", href: "/companies", icon: Building2 },
    { label: "Post Job", href: "/dashboard/recruiter/jobs/create", icon: PlusCircle },
    { label: "My Jobs", href: "/dashboard/recruiter/jobs", icon: Briefcase },
    { label: "Applicants", href: "/dashboard/recruiter/applicants", icon: Users },
    { label: "Shortlisted Candidates", href: "/dashboard/recruiter/shortlisted", icon: UserCheck },
    { label: "Task Round", href: "/dashboard/recruiter/tasks", icon: CheckSquare },
    { label: "Interviews", href: "/dashboard/recruiter/interviews", icon: Calendar },
    { label: "Hiring Decisions", href: "/dashboard/recruiter/hiring", icon: UserCheck },
    { label: "Notifications", href: "/notifications", icon: Bell },
    { label: "Settings", href: "/settings", icon: Settings },
  ],
  admin: [
    { label: "Dashboard Home", href: "/dashboard/admin", icon: LayoutDashboard },
    { label: "All Users", href: "/dashboard/admin/users", icon: Users },
    { label: "Recruiter Verification", href: "/dashboard/admin/approvals", icon: ShieldCheck },
    { label: "Job Approval Queue", href: "/dashboard/admin/jobs/pending", icon: FileCheck },
    { label: "All Jobs", href: "/dashboard/admin/jobs", icon: Briefcase },
    { label: "Reports / Analytics", href: "/dashboard/admin/reports", icon: BarChart3 },
    { label: "Close Job Requests", href: "/dashboard/admin/close-requests", icon: XCircle },
    { label: "Notifications", href: "/notifications", icon: Bell },
    { label: "Platform Settings", href: "/dashboard/admin/settings", icon: Settings },
  ],
};
